FROM saschazegerman/loginbuddy-oidcdr:latest

#COPY plugins-1.0.0.jar /usr/local/tomcat/shared/plugins-1.0.0.jar
#COPY plugins-1.0.0.jar /usr/local/tomcat/lib/loginbuddy-plugins.jar
#COPY plugins-1.0.0.jar /usr/local/tomcat/webapps/ROOT/WEB-INF/lib/plugins-1.0.0.jar
#COPY classes/ /usr/local/tomcat/webapps/ROOT/WEB-INF/classes
#COPY classes/ /usr/local/tomcat/shared
#COPY tools-plugin-verifier-1.0.0-jar-with-dependencies.jar /usr/local/tomcat/webapps/ROOT/WEB-INF/plugins/tools-plugin-verifier-dependencies-1.0.0.jar
#COPY tools-plugin-verifier-1.0.0.jar /usr/local/tomcat/webapps/ROOT/WEB-INF/plugins/tools-plugin-verifier-1.0.0.jar
COPY tools-plugins-1.0.0.jar /usr/local/tomcat/webapps/ROOT/WEB-INF/plugins/tools-plugins-1.0.0.jar
#COPY tools-plugins-1.0.0-jar-with-dependencies.jar /usr/local/tomcat/webapps/ROOT/WEB-INF/plugins/tools-plugins-1.0.0.jar