#
# This docker compose file is usable for development purposes:
#
# NOTE: use this only for local development purposes!
#
# IMPORTANT:
# loginbuddy-sidecar should NOT expose ports in an 'online' scenario! Port 444 is available to other
# containers within the same docker network by default! Do NOT include a port mapping!
# Here it is done for testing purposes only!
#
version: '3.4'
services:

  loginbuddy-demoserver:
    image: saschazegerman/loginbuddy-demoserver:latest
    restart: always
    hostname: demoserver.loginbuddy.net
    ports:
    - "443:443"
    - "8003:8003"
    environment:
      - "DEMOSERVER_LOCATION=https://loginbuddy-demoserver"
      - "DEMOSERVER_HOSTNAME=loginbuddy-demoserver"
      - "DEMOSERVER_SSL_PORT=443"
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8003,suspend=n,server=y"

  loginbuddy-oidcdr:
    image: saschazegerman/loginbuddy-oidcdr:latest
    restart: always
    depends_on:
      - loginbuddy-demoserver
    ports:
      - "8002:8002"
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8002,suspend=n,server=y"
      - "SSL_TRUSTED_SERVER=loginbuddy-demoserver:443"

  loginbuddy-sidecar:
    image: saschazegerman/loginbuddy-sidecar:latest
    restart: always
    depends_on:
      - loginbuddy-oidcdr
    ports:
      - "444:444"
      - "8044:8044"
      - "8001:8001"
      - "9011:9011"
      - "9012:9012"
    volumes:
      - ./config.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/config.json
      - ./configTemplates.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/configTemplates.json
      - ./discovery.json:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/discovery.json
      - ./permissions.policy:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/permissions.policy
    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,address=*:8001,suspend=n,server=y \
        -Dcom.sun.management.jmxremote \
        -Dcom.sun.management.jmxremote.authenticate=false \
        -Dcom.sun.management.jmxremote.ssl=false \
        -Dcom.sun.management.jmxremote.port=9011 \
        -Djava.rmi.server.hostname=local.loginbuddy.net \
        -Dcom.sun.management.jmxremote.rmi.port=9012 \
        -Dcom.sun.management.jmxremote.local.only=false"
      - "SUPPORT_OIDCDR=true"